export const MOTION_CHECK_INTERVAL = 1000;
export const MOTION_RESET_DELAY = 3000;
export const CAMERA_INIT_DELAY = 1000;
export const STATUS_UPDATE_INTERVAL = 60000;
export const LOW_BATTERY_THRESHOLD = 15;
export const MOTION_DETECTION_PHOTO_QUALITY = 0.1;
export const SIZE_CHANGE_THRESHOLD = 2;
export const WARMUP_FRAMES = 2;